# This Notebook builds different statistical tools for helping an Analyst

### Section deals with Matrix manipulations 

In [1]:
# Generate matrix transpose
import numpy as np

array = np.array([[1,1,0],[0,1,1]])

print(array.transpose())

[[1 0]
 [1 1]
 [0 1]]


In [2]:
array = np.array([[-2,8,20],[14,19,10],[2,-2,1]])

print(array.transpose())

[[-2 14  2]
 [ 8 19 -2]
 [20 10  1]]


In [ ]:
# Matrix multiplication
array = np.array([[1,1,0],[0,1,1]])

print(np.matmul(array.transpose(), array))
print(np.matmul(array, array.transpose()))

[[1 1 0]
 [1 2 1]
 [0 1 1]]
[[2 1]
 [1 2]]


In [6]:
array = np.array([[-2,14,2],[8,19,-2],[20,10,1]])

print(np.matmul(array.transpose(), array))
print(np.matmul(array, array.transpose()))

[[468 324   0]
 [324 657   0]
 [  0   0   9]]
[[204 246 102]
 [246 429 348]
 [102 348 501]]


### This section tool takes care of SVD related mathematical operations

In [ ]:
# Load required libraries
from matplotlib.image import imread
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
array = np.array([[4,1,0],[1,3,1],[0,1,2]])

U, S, VT = np.linalg.svd(array, full_matrices=False)

print(U)

print(np.diag(S))

print(VT)


[[-0.78867513  0.57735027  0.21132487]
 [-0.57735027 -0.57735027 -0.57735027]
 [-0.21132487 -0.57735027  0.78867513]]
[[4.73205081 0.         0.        ]
 [0.         3.         0.        ]
 [0.         0.         1.26794919]]
[[-0.78867513 -0.57735027 -0.21132487]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.21132487 -0.57735027  0.78867513]]


In [15]:
import numpy as np

X = np.random.randn(10,2) * np.sqrt(2. / 5)
X

array([[-1.0995174 , -0.53295803],
       [ 1.47770121, -1.31177837],
       [ 0.4730099 ,  0.99865048],
       [ 0.50299233, -0.12829668],
       [ 0.48886505,  0.2031412 ],
       [-0.78115695, -0.24295456],
       [-1.02014883, -0.83486263],
       [-0.21237755,  0.72558451],
       [-1.20328647, -0.16956099],
       [-0.02231373, -0.31743959]])

In [ ]:
np.random.uniform(-1, 1, (10, 1))
Y = np.random.normal(-1, 1, (10,1))
Y

array([[-0.92452641],
       [-1.58423138],
       [ 0.72625662],
       [-1.52640576],
       [-2.52582633],
       [-0.39726288],
       [-0.24276112],
       [-2.49810888],
       [ 0.90896194],
       [ 0.57149658]])

In [16]:
np.array(X).reshape(-1,1)

array([[-1.0995174 ],
       [-0.53295803],
       [ 1.47770121],
       [-1.31177837],
       [ 0.4730099 ],
       [ 0.99865048],
       [ 0.50299233],
       [-0.12829668],
       [ 0.48886505],
       [ 0.2031412 ],
       [-0.78115695],
       [-0.24295456],
       [-1.02014883],
       [-0.83486263],
       [-0.21237755],
       [ 0.72558451],
       [-1.20328647],
       [-0.16956099],
       [-0.02231373],
       [-0.31743959]])

In [20]:
X1 = np.random.rand(2,1)
X1

array([[0.46309172],
       [0.86289552]])

In [22]:
X2 = np.random.rand(2,1)
X2

array([[0.03469466],
       [0.78056332]])

In [25]:
X = np.column_stack((X1, X2))
X

array([[0.46309172, 0.03469466],
       [0.86289552, 0.78056332]])

In [27]:
X.shape

(2, 2)