# This Notebook builds different statistical tools for helping an Analyst

### Section deals with Matrix manipulations 

In [1]:
# Generate matrix transpose
import numpy as np

array = np.array([[1,1,0],[0,1,1]])

print(array.transpose())

[[1 0]
 [1 1]
 [0 1]]


In [2]:
array = np.array([[-2,8,20],[14,19,10],[2,-2,1]])

print(array.transpose())

[[-2 14  2]
 [ 8 19 -2]
 [20 10  1]]


In [ ]:
# Matrix multiplication
array = np.array([[1,1,0],[0,1,1]])

print(np.matmul(array.transpose(), array))
print(np.matmul(array, array.transpose()))

[[1 1 0]
 [1 2 1]
 [0 1 1]]
[[2 1]
 [1 2]]


In [6]:
array = np.array([[-2,14,2],[8,19,-2],[20,10,1]])

print(np.matmul(array.transpose(), array))
print(np.matmul(array, array.transpose()))

[[468 324   0]
 [324 657   0]
 [  0   0   9]]
[[204 246 102]
 [246 429 348]
 [102 348 501]]


### This section tool takes care of SVD related mathematical operations

In [ ]:
# Load required libraries
from matplotlib.image import imread
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
array = np.array([[4,1,0],[1,3,1],[0,1,2]])

U, S, VT = np.linalg.svd(array, full_matrices=False)

print(U)

print(np.diag(S))

print(VT)


[[-0.78867513  0.57735027  0.21132487]
 [-0.57735027 -0.57735027 -0.57735027]
 [-0.21132487 -0.57735027  0.78867513]]
[[4.73205081 0.         0.        ]
 [0.         3.         0.        ]
 [0.         0.         1.26794919]]
[[-0.78867513 -0.57735027 -0.21132487]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.21132487 -0.57735027  0.78867513]]
