In [1]:
import numpy as np

a = np.array([1,2])
print(a.dtype)

int32


In [6]:
b = np.array([1.0,2.0])
print(b.dtype)

float64


In [4]:
c = np.array([1.0,2.0], dtype=np.int64)
print(c.dtype)

int64


In [8]:
u = np.array([1.0,2.0])
v = np.array([3.0, 4.0])

print(f"{u.dot(v)}")
print(f"{np.dot(u, v)}")

11.0
11.0


In [10]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6],[7,8]])

print(f"{x.dot(v)}")
print(f"{np.dot(y,u)}")

print(f"{np.dot(x,y)}")

[11. 25.]
[17. 23.]
[[19 22]
 [43 50]]


In [ ]:
print(np.sum(x))

print(np.sum(x, axis=0)) # Compute sum of each column

print(np.sum(x, axis=1)) # Compute sum of each row

10
[4 6]
[3 7]


In [ ]:
# Transpose for a 2-D Matrix
print(x)
print(x.T)

# Transpose for a 1-D Matrix
print(u)
print(u.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1. 2.]
[1. 2.]


In [ ]:
# Numpy Broadcasting
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4,1))
print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [16]:
p = np.array([1,2,3])
q = np.array([4,5])
print(np.reshape(p, (3,1)))
print(np.reshape(p, (3,1)) * q)

[[1]
 [2]
 [3]]
[[ 4  5]
 [ 8 10]
 [12 15]]


In [18]:
x= np.array([[1,2,3],[4,5,6]])

print(x+p)

[[2 4 6]
 [5 7 9]]
