# Class-6: focussed on Python Braodcasting concept

Many real time use-case involves matrix of different dimension. Braodcasting helps in operations on these matrix

Rule:
 - Both the matrix shall be of same dimension
 - One of the matrix dimension should be 1 - so that it can be streched and map.

In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a * b

print(result)

[ 4 10 18]


## Examples for Broadcasting

Following example block leads to an error

In [2]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a2 = np.array([[1],[2],[3],[4]])

print(a1.shape)
print(a2.shape)

result = a1*a2

print(result)

(2, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

---

Following block shows that if one of the dimension is matching then Broadcasting can be applied


In [3]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a2 = np.array([[1],[2],[3],[4]])

print(a1.shape)
print(a2.shape)

result = a1*a2

print(result)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


---
In following example we see both the matrix are extended/streched

a1 is of size of 3x1

a2 is of size of 1x3

result is of size 3x3 (both matrix dimension strecthed)

In [4]:
a1 = np.array([[0,1,2]])
a2 = np.array([[0],[1],[2]])

print(a1.shape)
print(a2.shape)

result = a1 * a2

print(result)

(1, 3)
(3, 1)
[[0 0 0]
 [0 1 2]
 [0 2 4]]


---
Following code block shows addition operation.

np.ones creates a matrix of specified size pre-populated with 1

In [7]:
a1 = np.ones((3,3), dtype=float)
print(a1)

a2 = np.array([1,2,3])

print(a1.shape)
print(a2.shape)

result = a1 + a2

print(result)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
(3,)
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


---
Following code demonstrates addition capability using Broadcasting

arange method creates an array of the given size, populated with values in range from 0 to the value
ones method creates a matrix of the specified size, populated with all values as 1

In [11]:
a1 = np.ones((2,3))
a2 = np.arange(3)

print(a1.shape)
print(a2.shape)

result = a1 + a2

print(result)

(2, 3)
(3,)
[[1. 2. 3.]
 [1. 2. 3.]]


---
Following code block demonstrates extension of the array

a1 is of size 10x1
a2 is of size 1x10

result is of size 10x10

In [12]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(a1.shape)
print(a2.shape)

result = a1 * a2

print(result)

(10,)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


---
End of the Notebook
---
