# Numpy

## Initialization

In [2]:
import numpy as np

In [3]:
# A 1-D array
d = np.array([1,2,3])
d

array([1, 2, 3])

In [4]:
# A 2-D array
d = np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Initialize using built in functions
d = np.zeros((2,2), dtype=int)
d

array([[0, 0],
       [0, 0]])

In [22]:
d = np.ones((2,3))
print(d.dtype)
d2 = np.ones((2,3), dtype=np.int64)
print(d2.dtype)
d = d.astype(np.int32)
d

float64
int64


array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [24]:
d = np.random.random((2,2))
d

array([[0.98872005, 0.98471948],
       [0.74391335, 0.05837071]])

In [26]:
d = d.astype(np.int32)
d

array([[0, 0],
       [0, 0]], dtype=int32)

In [28]:
d = np.eye(2,2)
d

array([[1., 0.],
       [0., 1.]])

In [31]:
d = np.eye(4,4, 0)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
d = np.full((2,3), 7)
d

array([[7, 7, 7],
       [7, 7, 7]])

## Slicing

In [33]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
#  [[2 3]
#  [6 7]]
b = a[:2, 1:3]
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [41]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]
print(row_r1, row_r1.shape)
row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)
row_r3 = a[1:3, 2:]
print(row_r3, row_r3.shape)

col_r1 = a[:, 1]
print(col_r1, col_r1.shape)
col_r2 = a[1:3, 2:3]
print(col_r2, col_r2.shape)




[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[ 7  8]
 [11 12]] (2, 2)
[ 2  6 10] (3,)
[[ 7]
 [11]] (2, 1)


## Integer Indexing

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])

# Interesting part: here the indexes getiing picked up are
# a[1,0] a[0,0] a[0,1]   => First row-index from first list and col-index from second list 
print(a[[1,0,0],[0,0,1]])


[3 1 2]


In [45]:
print(a)

# Mutating values for specific inidices can be achieved
a[[1,0,0],[0,0,1]] += 10
print("----")
print(a)


[[11 12]
 [13  4]
 [ 5  6]]
----
[[21 22]
 [23  4]
 [ 5  6]]


## Bool Indexing

In [46]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

bool_idx = a > 6

print(bool_idx)

print(a[bool_idx])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 7  8  9 10 11 12]


## Array Math

In [ ]:
# Add
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,6]])

print(a + b)
print(np.add(a,b))

[[ 4  6  9]
 [ 7  9 12]]
[[ 4  6  9]
 [ 7  9 12]]


In [65]:
# Subtract
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,6]])

print(a - b)
print(np.subtract(a,b))

[[-2 -2 -3]
 [ 1  1  0]]
[[-2 -2 -3]
 [ 1  1  0]]


In [64]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,6]])

print(a * b)
print(np.multiply(a,b))

[[ 3  8 18]
 [12 20 36]]
[[ 3  8 18]
 [12 20 36]]


In [66]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,6]])

print(a / b)
print(np.divide(a,b))

[[0.33333333 0.5        0.5       ]
 [1.33333333 1.25       1.        ]]
[[0.33333333 0.5        0.5       ]
 [1.33333333 1.25       1.        ]]


In [68]:
# Sum up all row values and column values
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,6]])

print("Column: ", np.sum(a, axis=0)) # Column add
print("Row: ", np.sum(a, axis=1)) # Row add

Column:  [5 7 9]
Row:  [ 6 15]


In [73]:
# Transpose of a matrix
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [77]:
# Arithmetic operation on Matrix
b = np.array([7,8,9])

(np.reshape(a.T, (2,3)) * b).T

array([[ 7, 35],
       [32, 24],
       [18, 54]])

## Broadcasting

In [47]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([0,1,0,2])

print(a+b)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


In [ ]:
# This leads to ValueError as b is of size 3
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([0,1,2])

print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([0,1,2])

# Ensure that the reshape value corresponds to number of elements in original array
# In this example possible values are: (4,3), (6,2), (12, 1) - any of these combinations
# with order exchanged
a = np.reshape(a, (4,3))
print(a)
print(a + b)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5])

a * b #Leads to value error as both are of different shape

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# Reshape a to single column form
# 1
# 2
# 3
#
np.reshape(a, (3,1)) * b

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [78]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([1,0,1])

c = np.tile(b, (4,1))
c


array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [79]:
a + c

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [ ]:
# Previously the objective achieved through tile creation and addition
# Same objective is achieved using broadcasting
a + b

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])