# Decision Tree 

## First approach just demonstrates decision tree using Iris dataset available 

In [1]:
# Step 1: Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
# Step 2: Load dataset (Iris dataset as example)
iris = load_iris()
X, y = iris.data, iris.target


In [6]:
# Step 3: Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

X_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [4]:
# Step 4: Initialize and train the decision tree
clf = DecisionTreeClassifier(
    criterion="gini",   # or "entropy"
    max_depth=3,        # limit depth to avoid overfitting
    random_state=42
)
clf.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,3
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [5]:
# Step 5: Make predictions
y_pred = clf.predict(X_test)

# Step 6: Evaluate accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0


## Second approach is to use the DecisionTree to build rule base classifier

In [7]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

In [8]:
# Step 1: Create dataset
data = {
    "destination": ["US", "UAE", "Somalia", "Canada", "UK"],
    "label": ["Visa required", "Visa on arrival", "Restricted travel", "Visa required", "Visa required"]
}
df = pd.DataFrame(data)

In [12]:
# Step 2: Encode categorical variables
from sklearn.preprocessing import LabelEncoder
dest_encoder = LabelEncoder()
label_encoder = LabelEncoder()

X = dest_encoder.fit_transform(df["destination"]).reshape(-1, 1)
print(X)
y = label_encoder.fit_transform(df["label"])
print(y)

[[4]
 [2]
 [1]
 [0]
 [3]]
[2 1 0 2 2]


In [13]:
# Step 3: Train decision tree
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X, y)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [15]:
# Step 4: Predict
test_destination = "India"
encoded_test = dest_encoder.transform([test_destination]).reshape(-1, 1)
pred = clf.predict(encoded_test)

print("Prediction:", label_encoder.inverse_transform(pred)[0])

ValueError: y contains previously unseen labels: 'India'

In [16]:
# New code set to handle the unseen data
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

In [17]:
# Step 1: Create dataset
data = {
    "destination": ["US", "UAE", "Somalia", "Canada", "UK"],
    "label": ["Visa required", "Visa on arrival", "Restricted travel", "Visa required", "Visa required"]
}
df = pd.DataFrame(data)

In [49]:
# Step 2: Encode categorical variables
from sklearn.preprocessing import LabelEncoder

class DestinationLabelEncoder(LabelEncoder):
    def fit_transform(self, y):
        # print(f"Call lands here: {y}")
        if 'Other' not in y.values:
            #o_series = pd.Series([])
            y[max(y.index)+1] = 'Other' 
        # print(f"Updated: {y}")
        fit = super().fit_transform(y)
        return fit

    def transform(self, y):
        if y not in self.classes_:
            y = ['Other']
        return super().transform(y)

dest_encoder = DestinationLabelEncoder()
label_encoder = LabelEncoder()
initial_size = len(df)
X = dest_encoder.fit_transform(df["destination"]).reshape(-1, 1)
if initial_size != len(X):
    print("Adding another label")
    new_entry = pd.DataFrame({"label": ["Restricted travel - Visa Required"]})
    df = pd.concat([df, new_entry], ignore_index=True)
    # print(df["label"])
y = label_encoder.fit_transform(df["label"])

print(f"Data now ready for training!")


Adding another label
Data now ready for training!


In [50]:
# Step 3: Train decision tree
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X, y)

print("Model Training completed!")

Model Training completed!


In [51]:
# Step 4: Predict
test_destination = "India"
encoded_test = dest_encoder.transform([test_destination]).reshape(-1, 1)
pred = clf.predict(encoded_test)

print("Prediction:", label_encoder.inverse_transform(pred)[0])

Prediction: Restricted travel - Visa Required


## Neural network - This is an overkill for the case. But lets build this.

In [55]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder

# Step 1: Define dataset
destinations = ["US", "UAE", "Somalia", "Canada", "UK"]
labels = ["Visa required", "Visa on arrival", "Restricted travel", "Visa required", "Visa required"]

# Step 2: Encode categorical data
dest_encoder = LabelEncoder()
label_encoder = LabelEncoder()

X = dest_encoder.fit_transform(destinations)
y = label_encoder.fit_transform(labels)

# Convert to tensors
X_tensor = torch.tensor(X, dtype=torch.long).unsqueeze(1)  # shape (n_samples, 1)
y_tensor = torch.tensor(y, dtype=torch.long)

# Step 3: Define a simple neural network
class TravelNN(nn.Module):
    def __init__(self, vocab_size, hidden_dim, output_dim):
        super(TravelNN, self).__init__()
        self.embedding = nn.Embedding(vocab_size, hidden_dim)
        self.fc = nn.Linear(hidden_dim, output_dim)
    
    def forward(self, x):
        x = self.embedding(x).view(-1, hidden_dim)
        return self.fc(x)
    
    def train(self):
        # Step 4: Training setup
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.01)

        # Step 5: Train
        for epoch in range(100):
            optimizer.zero_grad()
            outputs = model(X_tensor)
            loss = criterion(outputs, y_tensor)
            loss.backward()
            optimizer.step()        

    def predict(self, test_destination='IND'):
        # Step 6: Predict
        test_encoded = torch.tensor([dest_encoder.transform([test_destination])[0]], dtype=torch.long).unsqueeze(1)
        pred = model(test_encoded)
        pred_label = label_encoder.inverse_transform([torch.argmax(pred, dim=1).item()])

        return pred_label[0]

hidden_dim = 8
model = TravelNN(vocab_size=len(dest_encoder.classes_), hidden_dim=hidden_dim, output_dim=len(label_encoder.classes_))
model.train()

print(model.predict('UAE'))



Visa on arrival


In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Do I need a visa for the US and Canada. India also?")

print(doc.ents)
for ent in doc.ents:
    if ent.label_ == "GPE":   # Geopolitical entity
        print(f"Destination: {ent.text} -> {model.predict(ent.text)}" )


(US, Canada, India)
Destination: US -> Visa required
Destination: Canada -> Visa required


ValueError: y contains previously unseen labels: np.str_('India')